steps:
  - id: "Rodando teste unitário"
    name: "gcr.io/cloud-builders/go"
    env: ['PROJECT_ROOT=workspace']
    args: ['test', './src/']
  
  - id: "Rodando build da imagem"
    name: "gcr.io/cloud-builders/go"
    env: ['PROJECT_ROOT=workspace']
    args: ['build', './src/main.go']