steps:
  - id: "Rodando teste unitário"
    name: "gcr.io/cloud-builders/go"
    env: ['PROJECT_ROOT=workspace']
    args: ['test', './src/']
  
  - id: "Rodando build da imagem"
    name: "gcr.io/cloud-builders/go"
    env: ['PROJECT_ROOT=workspace']
    args: ['build', './src/main.go']
  
  - id: "Push da imagem para o Registry"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--build-arg'
    - 'version=1.24.0'
    - '-t'
    - 'gcr.io/$PROJECT_ID/go-sum:latest'
    - '.'
  - name: 'gcr.io/$PROJECT_ID/go-sum'
    args: ['version']
  
  images:
  - 'gcr.io/$PROJECT_ID/go-sum:latest'
  tags: ['cloud-builders-community']