steps:
  - id: "Rodando teste unitário"
    name: "gcr.io/cloud-builders/go"
    env: ['PROJECT_ROOT=workspace']
    args: ['test', './src/']
  
  - id: "Rodando build da imagem"
    name: "gcr.io/cloud-builders/go"
    env: ['PROJECT_ROOT=workspace']
    args: ['build', './src/main.go']
  
  - id: "Gerando build da imagem"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-build', '.']

images:
  - 'gcr.io/$PROJECT_ID/go-sum:latest'